version: "3.8"
services:
  api:
    build: ./api
    container_name: my_app_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: blog_c
    ports:
      - 3000:3000
    stdin_open: true
    tty: true